### ISSUE TITLE
Installtion Issue

### ISSUE THREAD

**Issue by vijayanmmm** [tvn-cosine/leptonica.net#1]
Kindly help to solve the Nuget installation issue, the error showing as below

Attempting to gather dependency information for package 'leptonica.net.1.75.0.1' with respect to project 'TestingTesseract', targeting '.NETFramework,Version=v4.0'
Gathering dependency information took 239.21 ms
Attempting to resolve dependencies for package 'leptonica.net.1.75.0.1' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'leptonica.net.1.75.0.1'
Resolved actions to install package 'leptonica.net.1.75.0.1'
Retrieving package 'leptonica.net 1.75.0.1' from 'nuget.org'.
Adding package 'leptonica.net.1.75.0.1' to folder 'C:\Users\User1\Documents\Visual Studio 2017\Projects\TestingTesseract\packages'
Added package 'leptonica.net.1.75.0.1' to folder 'C:\Users\User1\Documents\Visual Studio 2017\Projects\TestingTesseract\packages'
Install failed. Rolling back...
Package 'leptonica.net.1.75.0.1' does not exist in project 'TestingTesseract'
Removing package 'leptonica.net.1.75.0.1' from folder 'C:\Users\User1\Documents\Visual Studio 2017\Projects\TestingTesseract\packages'
Removed package 'leptonica.net.1.75.0.1' from folder 'C:\Users\User1\Documents\Visual Studio 2017\Projects\TestingTesseract\packages'
Executing nuget actions took 670.49 ms
Failed to add reference to 'pvt.cppan.demo.danbloomberg.leptonica-1.75.0'.
  Please make sure that the file is accessible, and that it is a valid assembly or COM component.
Time Elapsed: 00:00:00.9323908
========== Finished ==========

There is no other error details found in the error tab,...
Thanks in Advance

**Comment by tvn-cosine** [comment]
Please check that your application framework is set to 4.7.1.

Another package will soon be released to target Frameworks 4.5 and 4.6.  Until then please ensure your application uses framework 4.7.1.

**Comment by vijayanmmm** [comment]
Thank you, that have solved the issue..
