### ISSUE TITLE
Reading bmp to pix

### ISSUE THREAD

**Issue by whatohyou** [tvn-cosine/leptonica.net#2]
http://tpgit.github.io/Leptonica/bmpio_8c_source.html
Is this function available in this .net nuget package?

I'm trying to read bmp into memory stream then modify it's content then change it to pix to make it readable by tesseract.net .

**Comment by tvn-cosine** [comment]
Yes, it should be available. 
We found working with GDI+ quite problematic during times and would recommend using something else for in memory manipulations.

**Comment by tvn-cosine** [comment]
Re: [https://github.com/tvn-cosine/tesseract.net/issues/10#issuecomment-396529240](https://github.com/tvn-cosine/tesseract.net/issues/10#issuecomment-396529240)

@CSharpReaper , Thanks for code. This was implemented in the latest releases of the leptonica nuget packages.

var pix = Pix1.pixReadFromMemoryStream(System.IO.Stream stream);

https://www.nuget.org/packages/leptonica.net/.
https://www.nuget.org/packages/tesseract.net/.
