### ISSUE TITLE
Full Resolution Display

### ISSUE THREAD

**Issue by fdncred** [tvn-cosine/leptonica.net#4]
Is there a way to use pixDisplay() to show the image at full resolution instead of down-scaling it?
```cs
var boxa1 = pix.pixConnComp(out Pixa pixa1, 8);
var pix1 = pixa1.pixaDisplayRandomCmap(pix.Width, pix.Height);
var cmap = pix1.pixGetColormap();
cmap.pixcmapResetColor(0, 255, 255, 255);
pix1.Write("pix1.png", ImageFileFormatTypes.IFF_PNG);
pix1.pixDisplay(100, 100);
```
Thanks,
Darren

**Comment by tvn-cosine** [comment]
Hi, 

pixDisplay are only used for debugging purposes and downscalling automatically happens to ensure the unix environments that uses xv does not perform its own downscaling resulting in very bad quality.  You can read the full explanation [here](https://github.com/DanBloomberg/leptonica/blob/master/src/writefile.c).  

If you only want to display the new image why not use the default image viewer on your operating system.  Just call 

`System.Diagnostics.Process.Start(@"pix1.png");`
